# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20170913_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issuedata',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 9), null=True),
        ),
    ]
