# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20170924_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedata',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 10), null=True),
        ),
    ]
