# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20170925_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Div',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='SE', max_length=3),
        ),
    ]
